-- SQL Script to set up the RapidTuy database in Supabase
-- Go to the Supabase SQL Editor and run this complete query to set up the tables.

-- 1. Create 'motorizados' table
CREATE TABLE IF NOT EXISTS public.motorizados (
    id int4 PRIMARY KEY,
    nombre text NOT NULL,
    placa text NOT NULL,
    telefono text NOT NULL,
    estado int4 NOT NULL DEFAULT 1, -- 1 = Disponible, 2 = Ocupado, 3 = Fuera de Servicio, 4 = Bloqueado por Impago
    latitud float8 NOT NULL DEFAULT 10.2315,
    longitud float8 NOT NULL DEFAULT -66.8652,
    fecha_vencimiento int8 NOT NULL DEFAULT 0,
    ultimo_pago_monto float8 NOT NULL DEFAULT 0.0,
    ultimo_pago_fecha int8 NOT NULL DEFAULT 0,
    comentarios text NULL,
    updated_at int8 NOT NULL DEFAULT (extract(epoch from now()) * 1000)::int8
);

-- 2. Create 'trips' table
CREATE TABLE IF NOT EXISTS public.trips (
    id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    origen text NOT NULL,
    destino text NOT NULL,
    monto float8 NOT NULL,
    estado text NOT NULL DEFAULT 'PENDIENTE', -- 'PENDIENTE', 'ACEPTADO', 'RECHAZADO', 'TIMEOUT', 'COMPLETADO', 'CANCELADO'
    motorizado_id int4 NULL,
    segundos_restantes int4 NOT NULL DEFAULT 15,
    intentos_asignacion int4 NOT NULL DEFAULT 0,
    lista_negra_ids text NOT NULL DEFAULT '',
    created_at int8 NOT NULL DEFAULT (extract(epoch from now()) * 1000)::int8,
    updated_at int8 NOT NULL DEFAULT (extract(epoch from now()) * 1000)::int8
);

-- Enable Realtime for these tables (conditional safe addition)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_rel pr 
        JOIN pg_publication p ON p.oid = pr.prpubid 
        JOIN pg_class c ON c.oid = pr.prrelid 
        WHERE p.pubname = 'supabase_realtime' AND c.relname = 'motorizados'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.motorizados;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_rel pr 
        JOIN pg_publication p ON p.oid = pr.prpubid 
        JOIN pg_class c ON c.oid = pr.prrelid 
        WHERE p.pubname = 'supabase_realtime' AND c.relname = 'trips'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.trips;
    END IF;
END $$;

-- Set up Row Level Security (RLS) - for simplicity and developer/testing environments,
-- we'll allow public reads and writes, but you can secure this later.
ALTER TABLE public.motorizados ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trips ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist to prevent duplication errors
DROP POLICY IF EXISTS "Allow public select" ON public.motorizados;
DROP POLICY IF EXISTS "Allow public insert" ON public.motorizados;
DROP POLICY IF EXISTS "Allow public update" ON public.motorizados;
DROP POLICY IF EXISTS "Allow public delete" ON public.motorizados;

DROP POLICY IF EXISTS "Allow public select trips" ON public.trips;
DROP POLICY IF EXISTS "Allow public insert trips" ON public.trips;
DROP POLICY IF EXISTS "Allow public update trips" ON public.trips;
DROP POLICY IF EXISTS "Allow public delete trips" ON public.trips;

-- Recreate policies
CREATE POLICY "Allow public select" ON public.motorizados FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.motorizados FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.motorizados FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete" ON public.motorizados FOR DELETE USING (true);

CREATE POLICY "Allow public select trips" ON public.trips FOR SELECT USING (true);
CREATE POLICY "Allow public insert trips" ON public.trips FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update trips" ON public.trips FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete trips" ON public.trips FOR DELETE USING (true);
